# Generated by Django 4.1.2 on 2022-10-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_iot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot',
            name='indate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='iot',
            name='outdate',
            field=models.DateTimeField(),
        ),
    ]
