# Generated by Django 4.1.2 on 2022-10-31 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_iot_indate_alter_iot_outdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot',
            name='indate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='iot',
            name='outdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
