# Generated by Django 4.1.2 on 2022-10-31 23:14

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_iot_indate_alter_iot_outdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot',
            name='indate',
            field=models.DateTimeField(blank=True, default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='iot',
            name='outdate',
            field=models.DateTimeField(blank=True, default=django.db.models.functions.datetime.Now()),
        ),
    ]
